version: 2

sources:
  - name: public_trade_data
    description: "Documentation for the schema that stores trade-related data."
    tables:
      - name: individual_trade_transactions
        description: "Contains individual trade transaction records."
      - name: date_dimension
        description: "Provides date attributes for analysis."
      - name: transaction_volumes
        description: "Aggregated national transaction volumes."

  - name: public_commodity_data
    tables:
      - name: commodity_prices_pre_2024
        description: "Historical commodity prices before 2024."
      - name: commodity_indices_pre_2024
        description: "Historical commodity indices before the 2024 season."
      - name: aci_historical_data
        description: "Historical ACI data up to November 2024."
      - name: aei_historical_data
        description: "Historical AEI data up to November 2024."
      - name: logistics_grid
        description: "Logistics grid dimensions for commodity movement."

  - name: public_pricing_data
    tables:
      - name: historical_commodity_prices
        description: "Historical prices for various commodities."
      - name: historical_security_prices
        description: "Historical security prices."
      - name: commodity_metadata
        description: "Metadata for commodities."
      - name: matched_orders
        description: "Records of successfully matched transactions."
      - name: client_order_requests
        description: "Records of both successful and failed transactions."
      - name: security_data
        description: "Details of securities available for trade."
      - name: board_data
        description: "Information about trade boards."
      - name: location_data
        description: "Geographical locations of trade participants."
      - name: currency_data
        description: "Currency details for transactions."

  - name: public_warehouse_data
    tables:
      - name: grn_records
        description: "Goods receipt note records."
      - name: warehouse_dimension
        description: "Dimensions of warehouses and storage facilities."
